---
- name: Remove ENV file for {{ service_name }}_container.service
  file:
    path: "{{ sysconf_dir }}/{{ service_name }}"
    state: absent

- name: Disable and stop {{ service_name }}
  systemd:
    name: '{{ service_name }}_container.service'
    enabled: False
    state: stopped

- name: Remove unit {{ service_name }}_container.service
  file:
    path: /etc/systemd/system/{{ service_name }}_container.service
    state: absent

- name: Reload systemd units
  command: systemctl daemon-reload
  changed_when: False

